### ISSUE TITLE
argparse: use of dict over argparse class

### ISSUE THREAD

**Issue by dakotabenjamin** [edgarriba/OpenDroneMap#20]
Why do we use a dict of argument keys (i.e. `vars(parse.parse_args()`)rather than the argparse namespace for the arguments? Is there a specific reason?

**Comment by edgarriba** [comment]
There isn't. I had an issue here when reading the input variables, so this is how I fixed it. Anyways, if you find or know another way to keep as the original feel free to change it.

**Comment by dakotabenjamin** [comment]
OK I'll look into it.
