### ISSUE TITLE
libdc1394 error: Failed to initialize libdc1394

### ISSUE THREAD

**Issue by edgarriba** [edgarriba/OpenDroneMap#3]
Got this error when running OpenSfM process. Any idea @paulinus? Did some research and found that it comes from OpenCV when tries to access in hardware devices.

https://enlook.wordpress.com/2015/01/29/error-ctypes-error-libdc1394-error-failed-to-initialize-libdc1394/

**Comment by paulinus** [comment]
I would go for the solution you mention. Otherwise, try not installing libdc1394

**Comment by edgarriba** [comment]
solved. What's more, I force to remove libdc1394 if it's installed

**Comment by edgarriba** [comment]
:+1:
