### ISSUE TITLE
OpenSfM fails

### ISSUE THREAD

**Issue by edgarriba** [edgarriba/OpenDroneMap#5]
@paulinus, got this error. Any idea?

running PYTHONPATH=/home/vagrant/software/OpenDroneMap-edgarriba/SuperBuild/install/lib/python2.7/dist-packages /home/vagrant/software/OpenDroneMap-edgarriba/SuperBuild/src/opensfm/bin/run_all /home/vagrant/datasets/odm_data_benchmark/images/
Matching 0 image pairs
2015-11-23 15:44:14,030 reading features
2015-11-23 15:44:14,030 Merging features onto tracks
2015-11-23 15:44:14,030 Good tracks: 0
images 0
nonfisheye images 0
0 partial reconstructions in total.
Traceback (most recent call last):
  File "/home/vagrant/software/OpenDroneMap-edgarriba/SuperBuild/src/opensfm/bin/mesh", line 23, in <module>
    reconstructions = data.load_reconstruction()
  File "/home/vagrant/software/OpenDroneMap-edgarriba/SuperBuild/src/opensfm/opensfm/dataset.py", line 295, in load_reconstruction
    with open(self.__reconstruction_file(filename)) as fin:
IOError: [Errno 2] No such file or directory: '/home/vagrant/datasets/odm_data_benchmark/images/reconstruction.json'
b

**Comment by dakotabenjamin** [comment]
What was the command you ran?

**Comment by edgarriba** [comment]
run_all + path_to_images

**Comment by paulinus** [comment]
When you run `run_all path` opensfm will first look for a `path/image_list.txt` file. If present, it will read the list of images from it. Otherwise, it will look for images in `path/images`.  [Here](https://github.com/mapillary/OpenSfM/blob/master/opensfm/dataset.py#L35-L42) is the code doing that.

[When run form OpenDroneMap](https://github.com/OpenDroneMap/OpenDroneMap/blob/gh-pages/run.py#L730-L734), we first create the `image_list.txt` file on a folder called `opensfm`, then we run `run_all opensfm`.

**Comment by edgarriba** [comment]
Does this file does only contain the absolute path to the image in each line?

**Comment by paulinus** [comment]
One line per image with the relative path with respect to the dataset folder (the one containing the `image_list.txt` file)

**Comment by edgarriba** [comment]
still getting an error:

Traceback (most recent call last):
  File "/home/vagrant/software/OpenDroneMap-edgarriba/SuperBuild/src/opensfm/bin/focal_from_exif", line 20, in <module>
    data = dataset.DataSet(args.dataset)
  File "/home/vagrant/software/OpenDroneMap-edgarriba/SuperBuild/src/opensfm/opensfm/dataset.py", line 47, in **init**
    io.mkdir_p(p)
  File "/home/vagrant/software/OpenDroneMap-edgarriba/SuperBuild/src/opensfm/opensfm/io.py", line 202, in mkdir_p
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 20] Not a directory: '/home/vagrant/datasets/odm_data_benchmark/image_list.txt/exif'
b

quitting cause: 
    PYTHONPATH=/home/vagrant/software/OpenDroneMap-edgarriba/SuperBuild/install/lib/python2.7/dist-packages /home/vagrant/software/OpenDroneMap-edgarriba/SuperBuild/src/opensfm/bin/run_all /home/vagrant/datasets/odm_data_benchmark/image_list.txt
returned with code 256.

**Comment by edgarriba** [comment]
@paulinus are you assuming that images are inside project_path/images ??

**Comment by paulinus** [comment]
`bin/run_all /home/vagrant/datasets/odm_data_benchmark/image_list.txt`
should be
`bin/run_all /home/vagrant/datasets/odm_data_benchmark`

**Comment by edgarriba** [comment]
working! thanks!
