### ISSUE TITLE
configuration.sh

### ISSUE THREAD

**Issue by dakotabenjamin** [edgarriba/OpenDroneMap#6]
I'm trying to get this branch running locally but am running into errors during the superbuild cmake:

```
Traceback (most recent call last):
  File "/odm/SuperBuild/build/ecto/catkin_generated/generate_cached_setup.py", line 20, in <module>
    from catkin.environment_cache import generate_environment_script
ImportError: No module named catkin.environment_cache
CMake Error at /odm/SuperBuild/install/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/bin/python
  "/odm/SuperBuild/build/ecto/catkin_generated/generate_cached_setup.py")
  returned error code 1
Call Stack (most recent call first):
  /odm/SuperBuild/install/share/catkin/cmake/all.cmake:186 (safe_execute_process)
  /odm/SuperBuild/install/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:32 (find_package)


make[2]: *** [ecto/stamp/ecto-configure] Error 1
make[1]: *** [CMakeFiles/ecto.dir/all] Error 2
make: *** [all] Error 2
```

All I did was run configure.sh on a fresh 14.04 machine, is there some dependency I need to install to get this working?

**Comment by edgarriba** [comment]
Ideally all dependencies are installed by the script before running cmake.

Make sure that you set correctly your PYTHONPATH as explained here: http://answers.ros.org/question/194651/gentoo-genmsg-error-at-catkin-compile/

I'll also try to run it with a fresh machine.

**Comment by dakotabenjamin** [comment]
I set my PYTHONPATH to /odm/SuperBuild/build/catkin/devel/lib/python2.7/dist-packages/ where catkin was built and it worked.

**Comment by dakotabenjamin** [comment]
New Error: 

I vaguely remember reading a previous issues discussing ffmpeg, but I can't find it. 

```
/odm/SuperBuild/build/opencv/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:29: fatal error: ffmpeg/avformat.h: No such file or directory
 #include <ffmpeg/avformat.h>
```

EDIT: I just ran again and it finished

**Comment by edgarriba** [comment]
regarding catkin-pkg, you can install via:

```
 sudo apt-get install python-catkin-pkg
```

and ffmpeg, could you check that all apt dependencies from configure.sh are correctly installed?

**Comment by edgarriba** [comment]
@dakotabenjamin did you solve that? Cannot reproduce your error. I added small fixes in configure.sh. Give it a shot!

**Comment by dakotabenjamin** [comment]
I did get the configuration script to finish but ran into some runtime issues. I had to add ecto to the PYTHONPATH: `/odm/SuperBuild/build/catkin/devel/lib/python2.7/dist-packages/:/odm/SuperBuild/build/ecto/devel/lib/python2.7/dist-packages/`, and now I get this error: 

```
vagrant@vagrant-ubuntu-trusty-64:/odm$ python run.py --project-path /vagrant_data/odm_data/seneca/
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    import ecto
  File "/odm/SuperBuild/build/ecto/devel/lib/python2.7/dist-packages/ecto/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 184, in <module>
  File "/odm/SuperBuild/src/ecto/python/ecto/schedulers.py", line 49, in <module>
    from PySide.QtCore import QTimer
ImportError: No module named PySide.QtCore
```

Do I install PySide via pip or is it already somewhere I just have to direct PYTHONPATH to it?

**Comment by edgarriba** [comment]
try with

```
  sudo pip install pyside
```

I'll commit if it works

**Comment by dakotabenjamin** [comment]
It took a while, but it worked. Running a test dataset now.

**Comment by edgarriba** [comment]
nice!
